### ISSUE TITLE
ReadAllText no linux

### ISSUE THREAD

**Issue by FelixPaulo** [dotnet/dotnet-api-docs.pt-br#1]
Olla preciso desenvolver uma aplicação .net core para ler um arquivo .CSV, gostaria de saber se o ReadAllText funcionaria normalmente em um servidor linux ?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 896775e2-4f85-35f2-6de5-ce4c73157f77
* Version Independent ID: b97f3644-3681-9fd1-a7b5-52e994db2233
* Content: [File.ReadAllText Method (System.IO)](https://docs.microsoft.com/pt-br/dotnet/api/system.io.file.readalltext?view=netframework-4.7.2#applies-to)
* Content Source: [xml/System.IO/File.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.IO/File.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Olá, @FelixPaulo 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
