### ISSUE TITLE
Não deu certo

### ISSUE THREAD

**Issue by maxmx03** [dotnet/dotnet-api-docs.pt-br#11]
Eu criei um formulário que abre 3 formulários dentro dele, só que abre dentro do Web Browser e deu tudo certo abrir o 1° formulário só que quando eu vou abrir o segundo o formulário anterior continuar rodando em segundo plano e eu gostaria de fechar o primeiro e deixar aberto apenas o 2 formulário.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e95c0f7e-30a5-5744-10f2-fe65bb7fbfff
* Version Independent ID: 7eefe73a-c6d7-b6d2-2060-4a35344fb2da
* Content: [WebBrowser.Stop Method (System.Windows.Forms)](https://docs.microsoft.com/pt-br/dotnet/api/system.windows.forms.webbrowser.stop?view=netframework-4.8#feedback)
* Content Source: [xml/System.Windows.Forms/WebBrowser.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.Windows.Forms/WebBrowser.xml)
* Product: **dotnet-api**
* Technology: **system.windows**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Olá, @maxmx03 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
