### ISSUE TITLE
Bad typo.

### ISSUE THREAD

**Issue by ezverev** [dotnet/dotnet-api-docs.pt-br#2]
The default value is 10:00:00 AM. - that is wrong. Default value is 00:10:00 (ten minutes).

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 14402f22-655d-2706-551f-774339d2173b
* Version Independent ID: 03954271-65c7-1780-0c39-acee05738caf
* Content: [MachineSettingsSection.MaxTimeout Property (System.Transactions.Configuration)](https://docs.microsoft.com/pt-br/dotnet/api/system.transactions.configuration.machinesettingssection.maxtimeout?view=netframework-4.7.2)
* Content Source: [xml/System.Transactions.Configuration/MachineSettingsSection.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.Transactions.Configuration/MachineSettingsSection.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @ezverev 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
The English version has the correct value:
https://docs.microsoft.com/en-us/dotnet/api/system.transactions.configuration.machinesettingssection.maxtimeout?view=netframework-4.7.2

**Comment by CeciAc** [comment]
Hello, @ezverev

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/pt-br/dotnet/api/system.transactions.configuration.machinesettingssection.maxtimeout?view=netframework-4.7.2. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
