### ISSUE TITLE
Código e comentários traduzíveis

### ISSUE THREAD

**Issue by BelarminoVicenzo** [dotnet/dotnet-api-docs.pt-br#4]
Essa é a primeira vez que eu consulto o site em português, eu sempre consultei em inglês.
Agora que vejo fico completamente decepcionado com a comunidade Lusófona.
Dê que adiante escrever/traduzir o texto da página em português se o objectivo final que é o código está em inglês?
Alêm da tradução pela máquina, com o tempo eu acho que deviam ter criado versões em n idiomas. Se eu der o link para alguém, ele fica sem entender o código.
Por exemplo:
// Determine whether a tag begins the string.
      if (item.Trim().StartsWith("&lt;")) {

Mesmo que mais abaixo explicar o funcionamento do programa, o melhor seria ela saber de antemão o que esse Determine whether a tag... Significa.
O StartsWith, Trim e outros não podem ser traduzidos/adaptados para o nosso idioma, mas há muita coisa aí que dá.

Por quê não traduzir o código traduzível e os comentários?
// The example displays the following output: , isso pode ser traduzido

Console.WriteLine("The original strings:");  o conteúdo dentro das aspas pode ser traduzido.

Um exemplo: 
using System;

public class Examplo
{
    public static void Main()
    {
        string[] fonteDaString ;

        // Mostra a string inicial do array.
        Console.WriteLine("As strings originais:");
        Console.WriteLine("---------------------");
        foreach (var s in fonteDaString)
            Console.WriteLine(s);
        Console.WriteLine();

       

        // Mostra as string com as tags iniciais removidas.
        foreach (var s in fonteDaString)
            Console.WriteLine(FaixaDeInicioDeTags(s));
    }

    private static string FaixaDeInicioDeTags(string item)
    {
        // Determine se uma tag inicia a string.
        if (item.Trim().StartsWith("&lt;"))
        {
            // encontra a tag de fechamento.
            int ultimaLocalizacao = item.IndexOf("&gt;");
            // Remove a tag.
            if (ultimaLocalizacao &gt;= 0)
            {
                item = item.Substring(ultimaLocalizacao + 1);

                // Remova quaisquer tags de partida adicionais.
                item = FaixaDeInicioDeTags(item);
            }
        }

        return item;
    }
}
// O exemplo exibe a seguinte saída:
// As strings originais:
// ---------------------
// &lt;b&gt; Este é um texto em negrito &lt;/ b&gt;
// &lt;H1&gt; Este é um texto grande &lt;/ H1&gt;
// &lt;b&gt; &lt;i&gt; &lt;font color = green&gt; Isso tem várias tags &lt;/ font&gt; &lt;/ i&gt; &lt;/ b&gt;
// &lt;b&gt; Isso tem tags &lt;i&gt; incorporadas &lt;/ b&gt;. &lt;/ b&gt;
// &lt;Esta linha simplesmente começa com um menor que o símbolo, não deve ser modificada
//
// Strings após o início das tags foram removidas:
// -----------------------------------------------
// Este é um texto em negrito &lt;/ b&gt;
// Este é um texto grande &lt;/ H1&gt;
// Isso tem várias tags &lt;/ font&gt; &lt;/ i&gt; &lt;/ b&gt;
// Isso tem tags &lt;i&gt; incorporadas &lt;/ b&gt;. &lt;/ B&gt;
// &lt;Esta linha simplesmente começa com um menor que o símbolo, não deve ser modificada

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d9d4aca5-9f7b-19de-969f-3f54d2fab15e
* Version Independent ID: 394bb8e0-e246-17ef-18f8-d2b8ea72c0c7
* Content: [String.StartsWith Method (System)](https://docs.microsoft.com/pt-br/dotnet/api/system.string.startswith?redirectedfrom=MSDN&view=netframework-4.7.2#System_String_StartsWith_System_String_)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System/String.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Olá, @BelarminoVicenzo 

Agradecemos seus comentários. A página em questão foi traduzida por máquina, o que nem sempre é perfeitamente compreensível. Recentemente adicionamos uma opção "Ler em inglês" à direita, que permite alternar para a versão em inglês sem precisar alterar as configurações de idioma. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by BelarminoVicenzo** [comment]
O ponto aqui não é ser máquina ou não a traduzir, a máquina está a traduzir a página parcialmente.

Se eu já estou a reclamar por não estar no nosso idioma ainda vez e dizes-me que adicionamos a opcção ler em inglês? 
Eu falo dos comentários e da parte do código que se pode traduzir.
Ehpah! Mãe, vocês sabem o que fazem... Força aí.

**Comment by JasonCard** [comment]
Hi @BelarminoVicenzo 

Thank you for your feedback.
The examples of comments and translatable content within code are "code snippets" that users can copy for their use. Currently, we are not localizing "code snippets". It can be very complicated to determine which parts of the code are comments or translatable content. Syntax of comments can be different depending on the programming language. So it is very risky to try and machine translate or even human translate code. And we want to avoid the risk of introducing errors and breaking the code. 
We will certainly take your feedback into consideration. We understand your inconvenience when comments within code could not be understood. 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

@CeciAc @DavidPrio #please-translate

**Comment by CeciAc** [comment]
@JasonCard translation

> Olá, @BelarminoVicenzo
> Agradecemos seus comentários.
> Os exemplos de comentários e de conteúdo que pode ser traduzido em códigos são ""snippets de código"" que os usuários podem copiar e usar. No momento, não estamos traduzindo esses ""snippets de código"", pois pode ser difícil determinar quais partes do código são comentários ou podem ser traduzidas. A sintaxe dos comentários pode ser diferente dependendo da linguagem de programação, então é muito arriscado tentar fazer uma tradução automática ou manual de códigos. Além disso, queremos evitar o risco de introduzir erros em códigos ou de corrompê-los. 
> Levaremos em consideração seus comentários e entendemos que, quando não se entende comentários dentro de um código, isso pode gerar transtornos.
> Apreciamos a sua contribuição para nossos artigos e esperamos que você continue fazendo comentários importantes.

**Comment by BelarminoVicenzo** [comment]
> @JasonCard translation
> 
> > Olá, @BelarminoVicenzo
> > Agradecemos seus comentários.
> > Os exemplos de comentários e de conteúdo que pode ser traduzido em códigos são ""snippets de código"" que os usuários podem copiar e usar. No momento, não estamos traduzindo esses ""snippets de código"", pois pode ser difícil determinar quais partes do código são comentários ou podem ser traduzidas. A sintaxe dos comentários pode ser diferente dependendo da linguagem de programação, então é muito arriscado tentar fazer uma tradução automática ou manual de códigos. Além disso, queremos evitar o risco de introduzir erros em códigos ou de corrompê-los.
> > Levaremos em consideração seus comentários e entendemos que, quando não se entende comentários dentro de um código, isso pode gerar transtornos.
> > Apreciamos a sua contribuição para nossos artigos e esperamos que você continue fazendo comentários importantes.

Mãe, você é bot ou quê?
Eu entendi e respondi de acordo. Não precisa traduzir!
