### ISSUE TITLE
Tradução para PT-BR está incorreta

### ISSUE THREAD

**Issue by fabiolg82** [dotnet/dotnet-api-docs.pt-br#5]
A tradução "Cria uma tarefa que será concluída quando todas as tarefas fornecidas forem concluídas." está incorreta.
Seria "Cria uma tarefa que será concluída quando qualquer uma das tarefas fornecidas foi concluída"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 1c50eacd-df85-b770-8975-b7bcc8cd3de2
* Version Independent ID: 6c1ba1c9-bbea-708d-1acb-992ffe03ee26
* Content: [Task.WhenAny Method (System.Threading.Tasks)](https://docs.microsoft.com/pt-br/dotnet/api/system.threading.tasks.task.whenany?view=netframework-4.7.2)
* Content Source: [xml/System.Threading.Tasks/Task.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.Threading.Tasks/Task.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Olá, @fabiolg82 
 
Agradecemos seus comentários. 
 
Vamos analisar seus comentários e daremos um retorno para você em breve. 
 
Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Olá, @fabiolg82 

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/dotnet/api/system.threading.tasks.task.whenany?view=netframework-4.7.2

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
