### ISSUE TITLE
Tradução para o inglês

### ISSUE THREAD

**Issue by lucasnobredev** [dotnet/dotnet-api-docs.pt-br#7]
Quando eu clico para ler o artigo em inglês, alguns títulos ainda estão em português.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 201b1530-0b96-73aa-1cc4-522228018974
* Version Independent ID: 2b6787c4-31d0-0fa4-6ea0-6db290964b27
* Content: [InternalsVisibleToAttribute Class (System.Runtime.CompilerServices)](https://docs.microsoft.com/pt-br/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.CompilerServices/InternalsVisibleToAttribute.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.Runtime.CompilerServices/InternalsVisibleToAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #1834](https://github.com/dotnet/dotnet-api-docs/issues/1834) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Olá, @lucasnobredev 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/dotnet/dotnet-api-docs/issues/1834. 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
