### ISSUE TITLE
Descrição(tradução) incorreta

### ISSUE THREAD

**Issue by kukamed** [dotnet/dotnet-api-docs.pt-br#8]
A frase inicial: "Remove o objeto na parte superior do Stack sem removê-lo." deveria ser "Retorna o objeto na parte superior do Stack sem removê-lo."

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 71384e37-ecee-ee47-f34a-aee21ab4f7d5
* Version Independent ID: ce98876b-b61c-383c-af8b-8f9a1d7ad308
* Content: [Stack.Peek Method (System.Collections)](https://docs.microsoft.com/pt-br/dotnet/api/system.collections.stack.peek?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Collections/Stack.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.Collections/Stack.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Olá, @kukamed 
 
Agradecemos seus comentários. 
 
Vamos analisar seus comentários e daremos um retorno para você em breve. 
 
Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Olá, @kukamed
 
Agradecemos seus comentários. 
 
Vamos analisar seus comentários e daremos um retorno para você em breve. 
 
Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Olá, @kukamed 

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/dotnet/api/system.collections.stack.peek?view=netframework-4.7.2

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
